import fs from 'fs';
import os from 'os';
import path from 'path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

const ORIGINAL_ENV = { ...process.env };
let dataDir = '';

async function loadBrain() {
    vi.resetModules();
    dataDir = fs.mkdtempSync(path.join(os.tmpdir(), 'open-pipi-brain-wiki-'));
    process.env = { ...ORIGINAL_ENV, DATA_DIR: dataDir, GEMINI_API_KEY: '' };
    return {
        brain: await import('./brain'),
        wiki: await import('./brain-wiki'),
        store: await import('./brain-store'),
    };
}

beforeEach(() => {
    process.env = { ...ORIGINAL_ENV };
});

afterEach(async () => {
    try {
        const store = await import('./brain-store');
        store.closeBrainDatabases();
    } catch {}
    process.env = { ...ORIGINAL_ENV };
    vi.restoreAllMocks();
    vi.resetModules();
    if (dataDir) fs.rmSync(dataDir, { recursive: true, force: true });
    dataDir = '';
});

const scope = { spaceId: 'telegram:chat-1' };

describe('core/brain-wiki', () => {
    it('projects wiki/index.md from the index, grouped by topic', async () => {
        const { brain, store } = await loadBrain();

        brain.updateWikiPage({ ...scope, path: 'people/anna.md', body: '# Anna\n\nEvening routine and sleep debt.' });
        brain.updateWikiPage({
            ...scope,
            path: 'projects/renovation.md',
            body: '# Renovation\n\nContractor timeline.',
        });

        const indexPath = path.join(store.getBrainScopeRoot(scope), 'wiki', 'index.md');
        const index = fs.readFileSync(indexPath, 'utf-8');

        expect(index).toContain('# Knowledge Base Index');
        expect(index).toContain('## people');
        expect(index).toContain('## projects');
        expect(index).toContain('[Anna](people/anna.md)');
        expect(index).toContain('[Renovation](projects/renovation.md)');
        // The index is a page catalogue, not a page.
        expect(brain.listWikiPages(scope).map((page) => page.path)).not.toContain('index.md');
    });

    it('refuses direct edits to the generated index and the append-only log', async () => {
        const { brain } = await loadBrain();

        expect(() => brain.updateWikiPage({ ...scope, path: 'index.md', body: '# Mine now' })).toThrow(
            /generated by the Brain Layer/
        );
        expect(() => brain.updateWikiPage({ ...scope, path: 'log.md', body: '# Mine now' })).toThrow(
            /generated by the Brain Layer/
        );
    });

    it('appends grep-able log entries and reads them back', async () => {
        const { brain, store } = await loadBrain();

        brain.appendWikiLog({
            ...scope,
            action: 'ingest',
            subject: 'Sleep debt and afternoon focus',
            details: { Disposition: 'Update', Raw: 'raw/health/2026-08-13-sleep-a1b2c3d4.md' },
            now: new Date('2026-08-13T10:00:00.000Z'),
        });
        brain.appendWikiLog({ ...scope, action: 'lint', subject: '6 issues found, 4 auto-fixed' });

        const logText = fs.readFileSync(path.join(store.getBrainScopeRoot(scope), 'wiki', 'log.md'), 'utf-8');
        expect(logText).toContain('## [2026-08-13] ingest | Sleep debt and afternoon focus');
        expect(logText).toContain('- Disposition: Update');
        // The heading prefix is the query interface: `grep "^## \[" log.md` must work.
        expect(logText.split('\n').filter((line) => line.startsWith('## ['))).toHaveLength(2);

        const entries = brain.readWikiLog(scope);
        expect(entries).toHaveLength(2);
        expect(entries[0].details.Raw).toBe('raw/health/2026-08-13-sleep-a1b2c3d4.md');
        expect(entries[1].action).toBe('lint');
    });

    it('records outbound links with their kind and whether they resolve', async () => {
        const { brain, store } = await loadBrain();

        brain.updateWikiPage({ ...scope, path: 'people/anna.md', body: '# Anna\n\nShort page.' });
        brain.updateWikiPage({
            ...scope,
            path: 'projects/renovation.md',
            body: [
                '# Renovation',
                '',
                'Discussed with [Anna](../people/anna.md) and sourced from [the thread](../../raw/home/thread.md).',
                '',
                '## See Also',
                '',
                '- [Missing Page](../people/nobody.md)',
            ].join('\n'),
        });

        const db = store.getBrainDb(scope);
        const links = db
            .prepare('SELECT to_path, kind, resolved FROM wiki_links WHERE from_path = ? ORDER BY to_path')
            .all('projects/renovation.md') as Array<{ to_path: string; kind: string; resolved: number }>;

        expect(links).toEqual([
            { to_path: 'raw/home/thread.md', kind: 'raw', resolved: 0 },
            { to_path: 'wiki/people/anna.md', kind: 'body', resolved: 1 },
            { to_path: 'wiki/people/nobody.md', kind: 'see_also', resolved: 0 },
        ]);
    });

    it('moves legacy nested entity pages up to a single topic level', async () => {
        const { store } = await loadBrain();

        const root = store.getBrainScopeRoot(scope);
        const legacyDir = path.join(root, 'wiki', 'entities', 'people');
        fs.mkdirSync(legacyDir, { recursive: true });
        fs.writeFileSync(path.join(legacyDir, 'anna.md'), '# Anna\n', 'utf-8');

        store.ensureBrainDirs(scope);

        expect(fs.existsSync(path.join(root, 'wiki', 'people', 'anna.md'))).toBe(true);
        expect(fs.existsSync(path.join(root, 'wiki', 'entities'))).toBe(false);
    });

    it('refuses an owner-only page to a member who knows the path', async () => {
        const { brain, wiki } = await loadBrain();

        brain.updateWikiPage({
            ...scope,
            path: 'health/private.md',
            body: '---\n{"visibility":"owner"}\n---\n# Private\n\nOwner-only content.',
        });
        brain.updateWikiPage({ ...scope, path: 'health/shared.md', body: '# Shared\n\nSpace content.' });

        // No person resolved: a background job sees only space-visible pages.
        const asJob = wiki.readWikiPageForReader({ ...scope, path: 'health/private.md' });
        expect(asJob.allowed).toBe(false);
        expect(asJob.content).toBe('');

        const shared = wiki.readWikiPageForReader({ ...scope, path: 'health/shared.md' });
        expect(shared.allowed).toBe(true);
        expect(shared.content).toContain('Space content.');

        expect(wiki.visibilityForReader({ ...scope })).toEqual(['space']);
        // The host-level wiki belongs to the owner.
        expect(wiki.visibilityForReader({})).toContain('owner');
    });

    it('reports a missing page without leaking whether it would have been readable', async () => {
        const { wiki } = await loadBrain();

        const page = wiki.readWikiPageForReader({ ...scope, path: 'health/nothing.md' });
        expect(page.exists).toBe(false);
        expect(page.allowed).toBe(true);
    });

    it('patches one section and leaves the rest of the page alone', async () => {
        const { brain, wiki } = await loadBrain();

        brain.updateWikiPage({
            ...scope,
            path: 'people/anna.md',
            body: '# Anna\n\n## Sleep\n\nOld sleep text.\n\n## Focus\n\nFocus text.\n\n### Detail\n\nNested detail.',
        });

        wiki.patchWikiSection({ ...scope, path: 'people/anna.md', heading: '## Sleep', body: 'New sleep text.' });
        const page = brain.readWikiPage('people/anna.md', scope);

        expect(page.content).toContain('New sleep text.');
        expect(page.content).not.toContain('Old sleep text.');
        expect(page.content).toContain('## Focus');
        expect(page.content).toContain('Focus text.');
        expect(page.content).toContain('Nested detail.');
    });

    it('appends a section that does not exist yet rather than failing', async () => {
        const { brain, wiki } = await loadBrain();

        brain.updateWikiPage({ ...scope, path: 'people/anna.md', body: '# Anna\n\n## Focus\n\nFocus text.' });
        wiki.patchWikiSection({ ...scope, path: 'people/anna.md', heading: 'Sleep', body: 'Brand new section.' });

        const page = brain.readWikiPage('people/anna.md', scope);
        expect(page.content).toContain('## Sleep');
        expect(page.content).toContain('Brand new section.');
        expect(page.content).toContain('Focus text.');
    });

    it('refuses to patch the generated index or the log', async () => {
        const { wiki } = await loadBrain();

        expect(() => wiki.patchWikiSection({ ...scope, path: 'index.md', heading: 'X', body: 'y' })).toThrow(
            /generated by the Brain Layer/
        );
    });
});
