const REPOSITORY_URL = 'https://github.com/amyotoff/open-pipi';

function escapeHtml(value: string): string {
    return value.replace(
        /[&<>"']/g,
        (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]!
    );
}

export function renderOnboardingLanding(origin?: string): string {
    const skillUrl = origin ? new URL('/agent-onboarding/SKILL.md', origin).href : '/agent-onboarding/SKILL.md';
    const prompt = origin
        ? `Ты работаешь как Codex в локальной задаче с терминалом. Сценарий: macOS. Официальный репозиторий: ${REPOSITORY_URL}. Инструкция: ${skillUrl}; резервная текстовая версия: ${new URL('/agent-onboarding/SKILL.txt', origin).href}. Проверь реальную целевую машину, каталог и существующую установку до команд. Не устанавливай в обычном ChatGPT, веб-чате или cloud sandbox. Для новой установки клонируй только официальный репозиторий и не перезаписывай файлы. Установи, настрой и запусти Open PiPi до первого подтверждённого ответа в Telegram. Секреты ввожу только я на приватной локальной странице. Фоновый режим — отдельный шаг.`
        : `Откройте ссылку SKILL.md на этой странице и скопируйте её полный адрес. Передайте адрес локальному Codex, Claude Code или Antigravity вместе с целевой машиной и официальным репозиторием ${REPOSITORY_URL}. Обычный ChatGPT и облачная песочница не могут выполнить установку на вашей машине.`;
    return `<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="description" content="Experimental Open PiPi automatic installation test bench for local coding agents.">
<title>Open PiPi automatic installation experiment</title><link rel="stylesheet" href="/agent-onboarding/onboarding.css"><script src="/agent-onboarding/onboarding.js" defer></script></head><body>
<header class="topbar"><a class="brand" href="/">Open PiPi / Lab</a><nav aria-label="Main navigation"><button id="language" class="language" type="button" aria-label="Switch to English">EN</button><a class="github" href="${REPOSITORY_URL}">GitHub</a></nav></header>
<main><section class="hero" aria-labelledby="title"><p class="wordmark">Installation Lab · Experimental MVP</p><h1 id="title" data-i18n="title">Автоматическая установка.</h1><p class="lead" data-i18n="lead">Тестовый стенд полностью автоматической установки.<br>Выберите локального coding agent и реальную целевую машину.</p><p class="experiment" data-i18n="experiment">Экспериментальная версия · результаты ещё проверяются</p></section>
<section class="handoff" aria-labelledby="handoff-title"><h2 id="handoff-title" data-i18n="cardTitle">Соберите точное поручение для локального агента.</h2><p class="support warning" data-i18n="agentNote">Обычный ChatGPT или другой веб-чат не может установить программу на вашем компьютере. Откройте coding agent с локальным терминалом.</p><p class="repository"><span data-i18n="officialRepo">Официальный репозиторий</span><br><a id="repository-link" href="${REPOSITORY_URL}">${REPOSITORY_URL}</a></p>
<div class="selectors"><label for="client"><span data-i18n="clientLabel">Локальный coding agent</span><select id="client"><option value="codex" data-i18n="clientCodex">Codex — локальная задача</option><option value="claude-code" data-i18n="clientClaude">Claude Code — терминал</option><option value="antigravity" data-i18n="clientAntigravity">Antigravity — агент редактора</option></select></label><label for="scenario"><span data-i18n="scenarioLabel">Целевая среда</span><select id="scenario"><option value="macos" data-i18n="scenarioMac">macOS</option><option value="linux" data-i18n="scenarioLinux">Linux</option><option value="windows" data-i18n="scenarioWindows">Windows через WSL2</option><option value="rpi" data-i18n="scenarioRpi">Raspberry Pi 64-bit</option><option value="vps" data-i18n="scenarioVps">VPS через SSH</option><option value="update" data-i18n="scenarioUpdate">Обновить установку</option></select></label></div><div class="guidance"><p id="client-guidance"></p><p id="scenario-note"></p></div>
<label for="prompt" class="label" data-i18n="promptLabel">Передайте этот текст выбранному агенту</label><textarea id="prompt" readonly spellcheck="false">${escapeHtml(prompt)}</textarea><button id="copy" class="primary" type="button" data-i18n="copy">Скопировать поручение</button><p id="copy-status" class="copy-status" role="status" aria-live="polite"></p><div class="card-footer"><a id="skill-link" href="${escapeHtml(skillUrl)}">SKILL.md</a><a id="skill-text-link" href="/agent-onboarding/SKILL.txt">SKILL.txt</a><span data-i18n="nothingInstalled">Копирование ничего не устанавливает</span></div></section>
<section class="journey" aria-label="Experiment checkpoints"><article><span class="number">01</span><h2 data-i18n="step1Title">Проверить цель.</h2><p data-i18n="step1Body">Агент подтверждает локальную машину, точную папку установки и существующую копию до команд.</p></article><article><span class="number">02</span><h2 data-i18n="step2Title">Установить безопасно.</h2><p data-i18n="step2Body">Новая установка и обновление идут разными путями; изменения и данные сохраняются.</p></article><article><span class="number">03</span><h2 data-i18n="step3Title">Доказать результат.</h2><p data-i18n="step3Body">Проверки проходят, пользователь вводит ключи приватно, реальный ответ проверяется отдельно.</p></article></section>
<section class="details" aria-labelledby="details-title"><h2 id="details-title" data-i18n="before">Границы эксперимента.</h2><details open><summary data-i18n="requirementsTitle">Какой агент подходит?</summary><p data-i18n="requirementsBody">Codex в локальной задаче, Claude Code в терминале или Antigravity с терминалом проекта. Обычная вкладка ChatGPT или Claude не имеет доступа к вашей машине.</p></details><details><summary data-i18n="targetsTitle">Какие цели поддерживаются?</summary><p data-i18n="targetsBody">Нативные macOS и Linux; Windows только через WSL2 Linux; Raspberry Pi с 64-bit Linux и Node.js 24; VPS только через выбранный вами сервер по SSH.</p></details><details><summary data-i18n="updateTitle">Как проходит обновление?</summary><p data-i18n="updateBody">Агент находит точную папку установки и данных, сохраняет локальные изменения и останавливается при конфликте.</p></details><details><summary data-i18n="privateTitle">Куда вводить секреты?</summary><p data-i18n="privateBody">Только вы вводите их на приватной локальной странице. Они не должны попадать в поручение, сайт или чат агента.</p></details><details><summary data-i18n="backgroundTitle">Запустится ли фоновый режим?</summary><p data-i18n="backgroundBody">Нет. Это отдельный шаг после локальной проверки и отдельного поручения пользователя.</p></details></section>
<noscript><p><strong>Нужен Codex, Claude Code или Antigravity с доступом к локальному терминалу.</strong> Обычный ChatGPT в браузере и облачная песочница не установят программу на вашу машину. Передайте агенту полный адрес <a href="${REPOSITORY_URL}">${REPOSITORY_URL}</a>, откройте <a href="${escapeHtml(skillUrl)}">SKILL.md</a> или текстовую версию <a href="/agent-onboarding/SKILL.txt">SKILL.txt</a> на этом же сайте. Попросите проверить машину и каталог до команд; ключи вводите сами, фоновый режим согласуйте отдельно.</p></noscript>
</main><footer><span>Open PiPi · Experimental MVP</span><nav aria-label="Documentation"><a href="/agent-onboarding/references/install.md" data-i18n="installGuide">Установка</a><a href="/agent-onboarding/references/troubleshooting.md" data-i18n="help">Диагностика</a><a href="/agent-onboarding/release.json" data-i18n="version">Сборка</a></nav></footer></body></html>`;
}
