function escapeHtml(value: string): string {
    return value.replace(
        /[&<>"']/g,
        (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]!
    );
}

export function renderOnboardingLanding(origin?: string): string {
    const skillUrl = origin ? new URL('/agent-onboarding/SKILL.md', origin).href : '/agent-onboarding/SKILL.md';
    const prompt = `Прочитай ${skillUrl} и помоги установить, настроить и запустить Open PiPi на этом компьютере до первого подтверждённого ответа в Telegram. Сначала проверь, нет ли существующей установки. Подключения и секреты я введу сам в приватной странице настройки. Фоновый режим выберу отдельно.`;
    return `<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="description" content="Give your coding agent one link. Set up your own Open PiPi assistant and verify its first Telegram reply.">
<title>Open PiPi agent onboarding</title><link rel="stylesheet" href="/agent-onboarding/onboarding.css">
<script src="/agent-onboarding/onboarding.js" defer></script></head><body>
<header class="topbar"><a class="brand" href="/">Open PiPi</a><nav aria-label="Main navigation"><button id="language" class="language" type="button" aria-label="Switch to English">EN</button><a class="github" href="https://github.com/amyotoff/open-pipi">GitHub</a></nav></header>
<main><section class="hero" aria-labelledby="title"><p class="wordmark">Open PiPi</p><h1 id="title" data-i18n="title">Привет, PiPi.</h1><p class="lead" data-i18n="lead">Ваш личный ассистент в Telegram.<br>Одна ссылка для агента — и можно начинать.</p><p class="experiment" data-i18n="experiment">Первая тестовая версия</p></section>
<section class="handoff" aria-labelledby="handoff-title"><h2 id="handoff-title" data-i18n="cardTitle">Поручите настройку своему агенту.</h2><p class="support" data-i18n="agentNote">Codex, Claude Code или другой агент с доступом к терминалу.</p><div class="choices" role="group" aria-label="Installation path"><button id="new-install" type="button" aria-pressed="true" data-i18n="newInstall">Новый PiPi</button><button id="existing-install" type="button" aria-pressed="false" data-i18n="existingInstall">Уже установлен</button></div><label for="prompt" class="label" data-i18n="promptLabel">Отправьте это сообщение агенту</label><textarea id="prompt" readonly spellcheck="false">${escapeHtml(prompt)}</textarea><button id="copy" class="primary" type="button" data-i18n="copy">Скопировать инструкцию</button><p id="copy-status" class="copy-status" role="status" aria-live="polite"></p><div class="card-footer"><a id="skill-link" href="${escapeHtml(skillUrl)}">SKILL.md</a><span data-i18n="nothingInstalled">Копирование ничего не устанавливает</span></div></section>
<section class="journey" aria-label="Setup steps"><article><span class="number">01</span><h2 data-i18n="step1Title">Агент готовит.</h2><p data-i18n="step1Body">Проверяет компьютер, устанавливает PiPi и открывает приватную страницу настройки.</p></article><article><span class="number">02</span><h2 data-i18n="step2Title">Вы подключаете.</h2><p data-i18n="step2Body">Подключаете AI, создаёте Telegram-бота и привязываете свой аккаунт на локальной странице.</p></article><article><span class="number">03</span><h2 data-i18n="step3Title">PiPi отвечает.</h2><p data-i18n="step3Body">Нажимаете «Попробовать сейчас» и пишете боту. Агент проверяет, что ответ действительно отправлен.</p></article></section>
<section class="details" aria-labelledby="details-title"><h2 id="details-title" data-i18n="before">Перед первым разговором.</h2><details open><summary data-i18n="requirementsTitle">Что понадобится?</summary><p data-i18n="requirementsBody">Компьютер с Git, Node.js 24+ и pnpm 10.26.2, coding agent с терминалом, Telegram и доступ к AI-провайдеру. Если чего-то нет, агент объяснит следующий шаг.</p></details><details><summary data-i18n="whereTitle">Где работает PiPi?</summary><p data-i18n="whereBody">На вашем компьютере. Этот сайт на Cloudflare раздаёт публичные инструкции. PiPi работает, пока компьютер включён и не спит; постоянный хостинг можно настроить позже.</p></details><details><summary data-i18n="costTitle">Что с оплатой моделей?</summary><p data-i18n="costBody">По умолчанию настройка использует OpenRouter. Использование моделей оплачивается отдельно от подписок ChatGPT и Claude.</p></details><details><summary data-i18n="privateTitle">Куда вводить ключи?</summary><p data-i18n="privateBody">Только на приватной странице настройки, которая откроется на вашем компьютере. Не отправляйте их в чат с агентом или на этот сайт.</p></details><details><summary data-i18n="doneTitle">Когда настройка завершена?</summary><p data-i18n="doneBody">Когда запущенный PiPi отправил ответ на ваше сообщение в Telegram. Установка файлов или сохранение настроек сами по себе ещё не подтверждают работающий диалог.</p></details></section>
<noscript><p>JavaScript выключен. Откройте <a href="${escapeHtml(skillUrl)}">SKILL.md</a> и передайте агенту полный адрес из браузера с просьбой установить, настроить и запустить PiPi.</p></noscript>
</main><footer><span>Open PiPi</span><nav aria-label="Documentation"><a href="/agent-onboarding/references/install.md" data-i18n="installGuide">Установка</a><a href="/agent-onboarding/references/troubleshooting.md" data-i18n="help">Помощь</a><a href="/agent-onboarding/release.json" data-i18n="version">Версия</a></nav></footer></body></html>`;
}
